INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (1, 'Zwettl', 'Am Tobel', 'Pizzeria Miam Miam', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (2, 'Zwettl', 'Niederstrahlbach 36', 'Wirtshaus Im Demutsgraben', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (3, 'Zwettl', 'Moidrams 1', 'Bergwirt Schrammel', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (4, 'Zwettl', 'Sprognitz 15', 'Bio Gasthaus Leibspeis', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (5, 'Zwettl', 'Dreifaltigkeitsplatz 3', 'Gasthaus zur Goldenen Rose', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (6, 'Armschlag', 'Salinenberg 3525', 'Mohnwirt Neuwiesinger', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (7, 'Krems', 'Dr Karl Strasse 23', '2Stein', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (8, 'Krems', 'Steiner Donaulaende', 'Blauenstein', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (9, 'Krems', 'Dreifaltigkeitsplatz 1', 'Stadtgasthaus Zum Goldenen Hirsch', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (10, 'Krems', 'Koernmarkt 9', 'Zum Kaiser von Österreich', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (11, 'Krems', 'Undstrasse 6', 'Late', 0);
INSERT INTO a_filialen (id, bezirk, adresse, name, version) VALUES (12, 'Krems', 'Suedtirolerplatz 2', 'Landhaus Bacher', 0);

INSERT INTO filialen (id) VALUES (1);
INSERT INTO filialen (id) VALUES (2);
INSERT INTO filialen (id) VALUES (7);
INSERT INTO filialen (id) VALUES (8);
INSERT INTO filialen (id) VALUES (9);

INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 3);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 4);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '07:45:00', 5);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '08:00:00', 6);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 10);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '08:00:00', 11);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 12);

INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (1, 'Adrian', 'Karl', '18011999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (2, 'Riccardo', 'Kropik', '07121890', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (3, 'Simon ', 'Garschall', '28111998', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (4, 'Jakob', 'Graser', '12031999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (5, 'Bernhard', 'Traschl', '26061999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (6, 'Julia ', 'Almeder', '16041999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (7, 'Jasmin', 'Köck', '13101999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (8, 'Stefan', 'Mayer', '13101998', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (9, 'Nico ', 'Windtner', '04081999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (10, 'Niklas', 'Mödlagl', '05031999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (11, 'Thomas', 'Himmer', '11111998', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (12, 'Patrick', 'Leister', '05071999', 0);
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr, version) VALUES (13, 'Nikolaus ', 'Draeger', '17091999', 0);

INSERT INTO kellner (id) VALUES (1);
INSERT INTO kellner (id) VALUES (2);
INSERT INTO kellner (id) VALUES (3);
INSERT INTO kellner (id) VALUES (5);
INSERT INTO kellner (id) VALUES (7);
INSERT INTO kellner (id) VALUES (10);

INSERT INTO koeche (id) VALUES (4);
INSERT INTO koeche (id) VALUES (6);
INSERT INTO koeche (id) VALUES (8);
INSERT INTO koeche (id) VALUES (9);
INSERT INTO koeche (id) VALUES (11);
INSERT INTO koeche (id) VALUES (12);
INSERT INTO koeche (id) VALUES (13);

INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (1, false, 1, 1, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (2, false, 2, 1, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (3, false, 3, 1, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (4, false, 4, 1, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (5, false, 1, 2, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (6, false, 2, 2, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (7, false, 3, 2, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (8, false, 4, 2, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (9, true, 1, 3, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (10, true, 2, 3, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (11, true, 3, 3, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (12, false, 4, 3, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (13, false, 5, 3, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (14, false, 1, 4, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (15, false, 2, 4, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (16, false, 3, 4, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (17, false, 4, 4, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (18, false, 5, 4, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (19, false, 1, 5, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (20, false, 2, 5, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (21, false, 3, 5, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (22, false, 4, 5, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (23, false, 1, 6, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (24, false, 2, 6, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (25, false, 3, 6, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (26, false, 4, 6, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (27, false, 1, 7, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (28, false, 2, 7, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (29, false, 1, 8, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (30, false, 2, 8, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (31, false, 1, 9, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (32, false, 2, 9, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (33, false, 3, 9, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (34, false, 4, 9, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (35, false, 1, 10, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (36, false, 2, 10, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (37, false, 3, 10, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (38, false, 1, 11, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (39, false, 2, 11, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (40, false, 3, 11, 0);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id, version) VALUES (41, false, 1, 12, 0);

INSERT INTO sessel (id, version, code, table_id) VALUES (1, 0, 'qwe', 1);
INSERT INTO sessel (id, version, code, table_id) VALUES (2, 0, 'wer', 1);
INSERT INTO sessel (id, version, code, table_id) VALUES (3, 0, 'tzu', 1);
INSERT INTO sessel (id, version, code, table_id) VALUES (4, 0, 'nht', 1);

INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (1, 'Kase', 20, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (2, 'Milch', 60, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (3, 'Cola', 1000, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (4, 'Mehl', 5000, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (5, 'Kartoffeln', 30, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (6, 'Karotten', 1000, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (7, 'Schokolade', 30, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (8, 'Cobe Rind', 30, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (9, 'Pute Brust', 40, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (10, 'Pute - Keule', 60, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (11, 'Reis', 80, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (12, 'Eier', 100, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (13, 'Gewuerzmischung', 40, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (14, 'Tomaten', 1000, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (15, 'Soja Souce', 30, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (16, 'Rind - Zunge', 50, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (17, 'Schweinsmedallion', 20, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (18, 'Zuccini', 3000, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (19, 'Zwiebeln', 200, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (20, 'Salat', 200, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (21, 'Chinakohl', 100, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (22, 'Schafkäse', 50, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (23, 'Maiskörner', 300, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (24, 'Tunfisch', 200, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (25, 'Panierpulver', 300, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (26, 'Faschiertes', 400, 0);
INSERT INTO zutaten (id, bezeichnung, lagerbestand, version) VALUES (27, 'Huhn ', 500, 0);

INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (1, 'VORSPEISE', 'Zuccinisuppe', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (2, 'VORSPEISE', 'Tomatensuppe', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (3, 'VORSPEISE', 'Klare Suppe', 2, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (4, 'VORSPEISE', 'Gulaschsuppe', 4, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (5, 'VORSPEISE', 'Fruehlingsrollen', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (6, 'VORSPEISE', 'ungarischer Eiaufstrich', 2, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (10, 'ZUSPEISE', 'griechischer Salat', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (11, 'ZUSPEISE', 'Bauernsalat', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (12, 'ZUSPEISE', 'Zuccinisalat', 3, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (13, 'ZUSPEISE', 'Tunfischsalat', 4, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (14, 'HAUPTSPEISE', 'Wienerschnitzel', 7, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (15, 'HAUPTSPEISE', 'Rindsbraten', 10, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (16, 'HAUPTSPEISE', 'Rindsgulasch', 8, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (17, 'HAUPTSPEISE', 'Rindsroulade', 8, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (18, 'HAUPTSPEISE', 'Krautrollen', 9, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (19, 'HAUPTSPEISE', 'gebackenes Haendel', 10, 0);
INSERT INTO gerichte (id, art, bezeichnung, preis, version) VALUES (20, 'HAUPTSPEISE', 'Huhngeschnetzeltes', 7, 0);

INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (4,2);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (4,5);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (4,14);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (4,17);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (6,18);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (6,19);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (6,20);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (8,1);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (8,2);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (8,3);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (8,4);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (8,4);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (9,20);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (9,19);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,11);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,13);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,14);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,18);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,20);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (11,1);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (12,2);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (12,3);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (12,4);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (13,5);
INSERT INTO koeche_gerichte(cook_id, dish_list_id) VALUES (13,6);

INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (3, 4, 1, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 5, 1, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 1, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 1, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (5, 14, 2, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 15, 2, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 2, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (2, 5, 3, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 16, 3, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 18, 3, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 3, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 4, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 4, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 4, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 2, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 9, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 18, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 26, 5, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 1, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 2, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 5, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 12, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 18, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 21, 6, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 12, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 14, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 18, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 20, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (2, 22, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 23, 10, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 6, 11, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 11, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 20, 11, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 22, 11, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 23, 11, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 1, 12, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 6, 12, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (2, 12, 12, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 12, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 18, 12, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 1, 13, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 15, 13, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 20, 13, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 22, 13, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 2, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (3, 5, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 9, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 11, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (2, 12, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 25, 14, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 15, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 8, 15, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 15, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 6, 16, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 8, 16, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 16, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 15, 16, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 1, 17, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 6, 17, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 8, 17, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 12, 17, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 15, 17, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 11, 18, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 18, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (2, 14, 18, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 21, 18, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 26, 18, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 2, 19, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 19, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 12, 19, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 19, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 27, 19, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 4, 20, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 13, 20, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 19, 20, 0);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id, version) VALUES (1, 27, 20, 0);

INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (1, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (3, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (5, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (1, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (7, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (13, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (9, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (7, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (11, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (3, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (12, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (10, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 7);

INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (1, '2018-02-02 08:36:04', 211, 'PAID', 0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (2, '2018-01-02 10:30:41', 212, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (3, '2018-01-02 13:37:04', 213, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (4, '2018-01-02 15:39:52', 214, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (5, '2018-01-03 08:40:20', 215, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (6, '2018-01-04 10:41:45', 216, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (7, '2018-01-04 13:44:13', 217, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (8, '2018-01-04 11:47:46', 218, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (9, '2018-01-07 12:56:43', 219, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (10, '2018-01-02 08:59:55', 220, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (11, '2018-11-05 12:13:50', 221, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (12, '2018-01-08 12:14:29', 222, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (13, '2018-01-02 13:10:28', 223, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (14, '2018-05-02 14:14:23', 224, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (15, '2018-01-02 15:13:14', 225, 'PAID',0);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id, verlauf, version) VALUES (16, '2018-01-01 14:17:11', 226, 'PAID',0);

INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (1, 1, 1, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (1, 11, 1, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (1, 18, 1, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (2, 10, 3, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (2, 11, 2, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (2, 14, 2, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (2, 20, 6, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (3, 3, 4, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (3, 16, 4, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (4, 4, 5, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (4, 6, 9, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (5, 5, 8, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (5, 19, 8, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (6, 14, 6, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (8, 11, 7, 0);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id, version) VALUES (21, 2, 6, 0);

INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 1);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 2);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 3);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 4);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 5);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 6);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 7);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 8);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 9);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 10);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 11);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 12);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 13);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 14);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 15);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 16);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 17);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 19);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 20);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 21);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 22);