INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (1, 'Zwettl', 'Am Tobel', 'Pizzeria Miam Miam');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (2, 'Zwettl', 'Niederstrahlbach 36', 'Wirtshaus Im Demutsgraben');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (3, 'Zwettl', 'Moidrams 1', 'Bergwirt Schrammel');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (4, 'Zwettl', 'Sprognitz 15', 'Bio Gasthaus Leibspeis');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (5, 'Zwettl', 'Dreifaltigkeitsplatz 3', 'Gasthaus zur Goldenen Rose');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (6, 'Armschlag', 'Salinenberg 3525', 'Mohnwirt Neuwiesinger');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (7, 'Krems', 'Dr Karl Strasse 23', '2Stein');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (8, 'Krems', 'Steiner Donaulaende', 'Blauenstein');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (9, 'Krems', 'Dreifaltigkeitsplatz 1', 'Stadtgasthaus Zum Goldenen Hirsch');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (10, 'Krems', 'Koernmarkt 9', 'Zum Kaiser von Österreich');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (11, 'Krems', 'Undstrasse 6', 'Late');
INSERT INTO a_filialen (id, bezirk, adresse, name) VALUES (12, 'Krems', 'Suedtirolerplatz 2', 'Landhaus Bacher');

INSERT INTO filialen (id) VALUES (1);
INSERT INTO filialen (id) VALUES (2);
INSERT INTO filialen (id) VALUES (7);
INSERT INTO filialen (id) VALUES (8);
INSERT INTO filialen (id) VALUES (9);

INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 3);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 4);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '07:45:00', 5);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '08:00:00', 6);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 10);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('18:00:00', '08:00:00', 11);
INSERT INTO filialen_gastgarten (schluss_zeit, oeffnungs_zeit, id) VALUES ('20:00:00', '08:00:00', 12);

INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (1, 'Adrian', 'Karl', '18011999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (2, 'Riccardo', 'Kropik', '07121890');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (3, 'Simon ', 'Garschall', '28111998');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (4, 'Jakob', 'Graser', '12031999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (5, 'Bernhard', 'Traschl', '26061999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (6, 'Julia ', 'Almeder', '16041999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (7, 'Jasmin', 'Köck', '13101999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (8, 'Stefan', 'Mayer', '13101998');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (9, 'Nico ', 'Windtner', '04081999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (10, 'Niklas', 'Mödlagl', '05031999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (11, 'Thomas', 'Himmer', '11111998');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (12, 'Patrick', 'Leister', '05071999');
INSERT INTO angestellte (id, vorname, nachname, sozialversicherungs_nr) VALUES (13, 'Nikolaus ', 'Draeger', '17091999');

INSERT INTO kellner (id) VALUES (1);
INSERT INTO kellner (id) VALUES (2);
INSERT INTO kellner (id) VALUES (3);
INSERT INTO kellner (id) VALUES (5);
INSERT INTO kellner (id) VALUES (7);
INSERT INTO kellner (id) VALUES (10);

INSERT INTO koeche (id) VALUES (4);
INSERT INTO koeche (id) VALUES (6);
INSERT INTO koeche (id) VALUES (8);
INSERT INTO koeche (id) VALUES (9);
INSERT INTO koeche (id) VALUES (11);
INSERT INTO koeche (id) VALUES (12);
INSERT INTO koeche (id) VALUES (13);

INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (1, false, 1, 1);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (2, false, 2, 1);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (3, false, 3, 1);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (4, false, 4, 1);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (5, false, 1, 2);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (6, false, 2, 2);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (7, false, 3, 2);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (8, false, 4, 2);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (9, true, 1, 3);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (10, true, 2, 3);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (11, true, 3, 3);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (12, false, 4, 3);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (13, false, 5, 3);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (14, false, 1, 4);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (15, false, 2, 4);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (16, false, 3, 4);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (17, false, 4, 4);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (18, false, 5, 4);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (19, false, 1, 5);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (20, false, 2, 5);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (21, false, 3, 5);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (22, false, 4, 5);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (23, false, 1, 6);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (24, false, 2, 6);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (25, false, 3, 6);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (26, false, 4, 6);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (27, false, 1, 7);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (28, false, 2, 7);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (29, false, 1, 8);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (30, false, 2, 8);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (31, false, 1, 9);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (32, false, 2, 9);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (33, false, 3, 9);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (34, false, 4, 9);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (35, false, 1, 10);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (36, false, 2, 10);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (37, false, 3, 10);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (38, false, 1, 11);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (39, false, 2, 11);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (40, false, 3, 11);
INSERT INTO tische (id, ist_raucher_tisch, tisch_nr, filiale_id) VALUES (41, false, 1, 12);

INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (1, 'Kase', 20);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (2, 'Milch', 60);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (3, 'Cola', 1000);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (4, 'Mehl', 500);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (5, 'Kartoffeln', 30);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (6, 'Karotten', 1000);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (7, 'Schokolade', 30);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (8, 'Cobe Rind', 30);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (9, 'Pute Brust', 40);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (10, 'Pute - Keule', 60);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (11, 'Reis', 80);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (12, 'Eier', 100);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (13, 'Gewuerzmischung', 40);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (14, 'Tomaten', 1000);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (15, 'Soja Souce', 30);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (16, 'Rind - Zunge', 50);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (17, 'Schweinsmedallion', 20);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (18, 'Zuccini', 300);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (19, 'Zwiebeln', 200);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (20, 'Salat', 200);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (21, 'Chinakohl', 100);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (22, 'Schafkäse', 50);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (23, 'Maiskörner', 300);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (24, 'Tunfisch', 200);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (25, 'Panierpulver', 300);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (26, 'Faschiertes', 400);
INSERT INTO zutaten (id, bezeichnung, lagerbestand) VALUES (27, 'Huhn ', 500);

INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (1, 'VORSPEISE', 'Zuccinisuppe', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (2, 'VORSPEISE', 'Tomatensuppe', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (3, 'VORSPEISE', 'Klare Suppe', 2);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (4, 'VORSPEISE', 'Gulaschsuppe', 4);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (5, 'VORSPEISE', 'Fruehlingsrollen', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (6, 'VORSPEISE', 'ungarischer Eiaufstrich', 2);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (10, 'ZUSPEISE', 'griechischer Salat', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (11, 'ZUSPEISE', 'Bauernsalat', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (12, 'ZUSPEISE', 'Zuccinisalat', 3);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (13, 'ZUSPEISE', 'Tunfischsalat', 4);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (14, 'HAUPTSPEISE', 'Wienerschnitzel', 7);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (15, 'HAUPTSPEISE', 'Rindsbraten', 10);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (16, 'HAUPTSPEISE', 'Rindsgulasch', 8);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (17, 'HAUPTSPEISE', 'Rindsroulade', 8);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (18, 'HAUPTSPEISE', 'Krautrollen', 9);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (19, 'HAUPTSPEISE', 'gebackenes Haendel', 10);
INSERT INTO gerichte (id, art, bezeichnung, preis) VALUES (20, 'HAUPTSPEISE', 'Huhngeschnetzeltes', 7);

INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (3, 4, 1);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 5, 1);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 1);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 1);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (5, 14, 2);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 15, 2);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 2);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (2, 5, 3);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 16, 3);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 18, 3);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 3);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 4);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 4);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 4);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 2, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 9, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 18, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 26, 5);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 1, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 2, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 5, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 12, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 18, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 21, 6);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 12, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 14, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 18, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 20, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (2, 22, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 23, 10);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 6, 11);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 11);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 20, 11);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 22, 11);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 23, 11);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 1, 12);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 6, 12);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (2, 12, 12);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 12);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 18, 12);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 1, 13);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 15, 13);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 20, 13);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 22, 13);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 2, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (3, 5, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 9, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 11, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (2, 12, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 25, 14);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 15);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 8, 15);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 15);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 6, 16);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 8, 16);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 16);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 15, 16);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 1, 17);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 6, 17);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 8, 17);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 12, 17);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 15, 17);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 11, 18);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 18);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (2, 14, 18);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 21, 18);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 26, 18);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 2, 19);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 19);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 12, 19);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 19);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 27, 19);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 4, 20);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 13, 20);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 19, 20);
INSERT INTO gerichte_zutaten (menge, zutat_id, gericht_id) VALUES (1, 27, 20);

INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (1, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (3, 1);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (5, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 2);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (1, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (7, 3);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (2, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (13, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (9, 4);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (7, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (11, 5);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (3, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (6, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (12, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (10, 6);
INSERT INTO filialen_angestellte (aemployee_id, branch_list_id) VALUES (4, 7);

INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (1, '2018-02-02 08:36:04', 211);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (2, '2018-01-02 10:30:41', 212);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (3, '2018-01-02 13:37:04', 213);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (4, '2018-01-02 15:39:52', 214);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (5, '2018-01-03 08:40:20', 215);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (6, '2018-01-04 10:41:45', 216);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (7, '2018-01-04 13:44:13', 217);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (8, '2018-01-04 11:47:46', 218);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (9, '2018-01-07 12:56:43', 219);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (10, '2018-01-02 08:59:55', 220);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (11, '2018-11-05 12:13:50', 221);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (12, '2018-01-08 12:14:29', 222);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (13, '2018-01-02 13:10:28', 223);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (14, '2018-05-02 14:14:23', 224);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (15, '2018-01-02 15:13:14', 225);
INSERT INTO bestellungen (id, bestellungs_zeitpunkt, bestellungs_id) VALUES (16, '2018-01-01 14:17:11', 226);

INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (1, 1, 1);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (1, 11, 1);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (1, 18, 1);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (2, 10, 3);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (2, 11, 2);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (2, 14, 2);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (2, 20, 6);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (3, 3, 4);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (3, 16, 4);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (4, 4, 5);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (4, 6, 9);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (5, 5, 8);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (5, 19, 8);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (6, 14, 6);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (8, 11, 7);
INSERT INTO bestellungen_tische_gerichte (tisch_id, gericht_id, bestellungs_id) VALUES (21, 2, 6);

INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 1);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 2);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 3);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (1, 4);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 5);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 6);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 7);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (2, 8);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 9);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 10);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 11);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 12);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (3, 13);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 14);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 15);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 16);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (5, 17);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 19);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 20);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 21);
INSERT INTO kellner_tische (waiter_id, table_list_id) VALUES (7, 22);


